In [1]:
import pandas as pd

In [3]:
#2 Main datatypes
brand = pd.Series(["BMW", "Toyota", "Honda"])
brand

0       BMW
1    Toyota
2     Honda
dtype: object

In [6]:
#Series = 1 Dimensional/Columns
colors = pd.Series(["Red", "Blue", "Green"])
colors

0      Red
1     Blue
2    Green
dtype: object

In [9]:
#Dataframe = 2 Dimensional
car_data = pd.DataFrame({"Car Make": brand, "Colors": colors})
car_data

  Car Make Colors
0      BMW    Red
1   Toyota   Blue
2    Honda  Green

In [10]:
#Importing Datasets
car_sales = pd.read_csv("car-sales.csv")
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [11]:
#axis=0 then its row and if the axis=1 then its column

In [ ]:
#Exporting the CSV

#car_sales.to_csv("exporting-practice.csv") Try this first and then use index
car_sales.to_csv("exporting-practice.csv", index=False)
#car_sales.to_excel("directly to excel")

In [19]:
exporting_practice = pd.read_csv("exporting-practice.csv")
exporting_practice

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

Describe Data

In [21]:
#Attributes
car_sales.dtypes

#Function
#car_sales.to_csv()

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [22]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [24]:
#Storing the columns so we can do some operations
car_column = car_sales.columns
car_column

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [26]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [27]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [28]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [30]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [32]:
car_sales.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [33]:
car_prices = pd.Series([1400, 3545, 4533, 4542])
car_prices.mean()

np.float64(3505.0)

In [34]:
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [35]:
car_sales["Doors"].sum()

np.int64(40)

In [36]:
len(car_sales)

10